config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :description
  has_many :comments

  validates_presence_of :title, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post, only: [:create, :destroy]

	def create
		@comment = @post.comments.build(comment_params)
		if @comment.save
			redirect_to root_path
		end
	end

	def destroy
		@comment = @post.comments.find_by(id: params[:id])
		@comment.destroy
		render turbo_stream: turbo_stream.remove("comment_#{@comment.id}")
	end

	private

	def comment_params
		params.require(:comment).permit(:text)
	end	

	def set_post
		@post = Post.find_by(id: params[:post_id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	def index
		@posts = Post.all
		@comment = Comment.new
	end

	def new
		@post = Post.new()
	end

	def show; end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] = 'Post created successfully!!'
		else
			flash[:alert] = @post.errors.full_messages.join(', ')
		end
		redirect_to root_path
	end

	def edit
		respond_to do |format|
			format.html
			format.turbo_stream { render turbo_stream: turbo_stream.update("post_#{@post.id}_edit", partial: 'edit_post_form') }
		end
	end

	def update
		if @post.update(post_params)
			respond_to do |format|
				format.html
				format.turbo_stream { render turbo_stream: turbo_stream.replace("post_#{@post.id}_edit", partial: 'post_detail', locals: { post: @post }) }
			end
		else
			render turbo_stream: turbo_stream.update("post_#{@post.id}_edit", partial: 'edit_post_form')
		end
	end
	
	def destroy
		@post.destroy
		render turbo_stream: turbo_stream.remove("post_#{@post.id}_edit")
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment_form.html.erb
<%= form_with(model: [post, @comment], url: post_comments_path(post_id: post)) do |form| %>
<div class="row">
	<div class="col-9">
		<%= form.text_field :text, placeholder: 'Add comment here', class: 'form-control' %>
	</div>
	<div class="col-3">
		<%= form.submit 'Add Comment', class: 'btn btn-outline-primary'%>
	</div>
</div>
<% end %>

app/views/comments/_comments.html.erb
<div id="comment_<%= comment.id %>">
	<span><%= comment.text %></span>
	<%= link_to post_comment_path(post, comment), class: 'text-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
		<i class="fa-regular fa-trash-can"></i>
	<% end %> 
	<% unless comment.eql?(post.comments.last) %>
		<hr />
	<% end %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application",
                            'https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css',
                            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css',
                             "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <% if flash[:notice] %>
        <p class="alert bg-success text-light m-0"><%= flash[:notice] %></p>
      <% elsif flash[:alert] %>        
        <p class="alert bg-danger text-light m-0"><%= flash[:alert] %></p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_edit_post_form.html.erb
<%= form_with(model: @post, class: "form") do |form| %>
<div class="card-header">
	<%= form.label :title, 'Title', class: 'form-label' %>
	<%= form.text_field :title, class: 'form-control' %>
	<% @post.errors.full_messages_for(:title).each do |message| %>
		<div class="errors text-danger"><%= message %></div>
	<% end %>
</div>
<div class="card-body">
	<%= form.label :description, 'Description', class: 'form-label' %>
	<%= form.rich_text_area :description, class: 'form-control' %>
	<% @post.errors.full_messages_for(:description).each do |message| %>
		<div class="errors text-danger"><%= message %></div>
	<% end %>

	<%= form.submit 'Submit', class: 'btn btn-primary mt-3' %>
	<%= link_to 'Cancel', root_path, class: 'btn btn-dark mt-3' %>
</div>
<% end %>

app/views/posts/_new_post_form_modal.html.erb
<div class="modal modal-lg fade" id="new_post_modal" tabindex="-1" aria-labelledby="label" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Add Post</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
			</div>
			<div class="modal-body">
				<%= form_with(model: @post, url: posts_path) do |form| %>
					<%= form.label :title, 'Title', class: 'form-label' %>
					<%= form.text_field 'post[title]', class: 'form-control' %>

					<%= form.label :description, 'Description', class: 'form-label' %>
					<%= form.rich_text_area 'post[description]', class: 'form-control' %>

					<%= form.submit 'Submit', class: 'btn btn-outline-primary mt-3' %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/_post_comments.html.erb
<div class="row">
	<div class="col-3">
		<span class="fw-bold">Add Comment:</span>
	</div>
	<div class="col-9" id="comment-form">
		<%= render partial: 'comments/comment_form', locals: {post: post} %>
	</div>
</div>
<div id="post-<%= post.id %>-comments">
	<% if post.comments.exists? %>
		<span class="fw-bold"><%= post.comments.count %> Comments</span>
	<% end %>
	<%= render partial: 'comments/comments', collection: post.comments, as: :comment, locals: { post: post } %>
</div>

app/views/posts/_post_detail.html.erb
<div class="card mb-2 mt-2" id="post_<%= post.id %>_edit">
	<div class="card-header">
		<%= link_to post.title, post_path(post), class: 'text-decoration-none fw-bolder' %>
		<div class="float-end">
			<%= link_to 'Edit', edit_post_path(post), class: 'btn btn-outline-dark', data: { turbo_stream: true } %>
			<%= link_to 'Delete', post_path(post), class: 'btn btn-outline-danger', data: { turbo_method: :delete, turbo_confirm: 'Do you really want to delete this post?' } %>
		</div>
	</div>
	<div class="card-body">
		<%= post.description %>
	</div>
	<div class="card-footer" id="post_<%= post.id %>_comments">
		<%= render partial: 'post_comments', locals: { post: post } %>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="section">
	<div class="container">
		<div class="back">
			<%= link_to 'Back', root_path, class: 'btn btn-primary' %>
		</div>
		<div class="post-form">
			<%= form_with(model: @post, class: "form") do |form| %>
				<%= form.label :title, 'Title', class: 'form-label' %>
				<%= form.text_field :title, class: 'form-control' %>

				<%= form.label :description, 'Description', class: 'form-label' %>
				<%= form.rich_text_area :description, class: 'form-control' %>

				<%= form.submit 'Submit', class: 'btn btn-secondary mt-3' %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="main">
	<div class="header text-center bg-dark">
		<%= link_to('#', class: 'btn btn-outline-primary text-light float-end mt-2 me-2', data: { bs_toggle: 'modal', bs_target: '#new_post_modal'}) do %>
			Create Post
		<% end %>
		<h1 class="text-light">Blogs</h1>	
	</div>
	<div class="container blogs">
		<% if @posts.present? %>
			<%= render partial: 'post_detail', collection: @posts, as: :post %>
		<% else %>
			<h2>There are currently no posts!!</h2>
		<% end %>
	</div>
	<%= render partial: 'new_post_form_modal' %>
</div>

app/views/posts/new.html.erb
<div class="section">
	<div class="container">
		<div class="back">
			<%= link_to 'Back', root_path, class: 'btn btn-primary' %>
		</div>
		<div class="post-form">
			<%= form_with(model: @post, class: "form") do |form| %>
				<%= form.label :title, 'Title', class: 'form-label' %>
				<%= form.text_field :title, class: 'form-control' %>

				<%= form.label :description, 'Description', class: 'form-label' %>
				<%= form.rich_text_area :description, class: 'form-control' %>

				<%= form.submit 'Submit', class: 'btn btn-secondary mt-3' %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="post-heading">
		<h2>Post</h2>
	</div>
	<div class="post-detail">
		<p>
			<span class="fw-bold">Title:</span>
			<span><%= @post.title %></span>
		</p>
		<p>
			<span class="fw-bold">Description:</span>
			<span><%= @post.description %></span>
		</p>
	</div>
	<%= link_to "Back", root_path, class: 'btn btn-primary' %>
</div>